INSERT INTO classification_society (nameEN, native_name, abbreviation, start_year, end_year, head_office, iacs_member)
VALUES ('Lloyd''s Register', null, 'LR', 1760, null, 'London', true),
       ('Bureau Veritas', null, 'BV', 1828, null, 'Paris', true),
       ('Austrian Veritas/Adriatic Veritas', null, 'AV', 1858, 1921, 'Trieste', null),
       ('Registro Italiafalse Navale', null, 'RINA', 1861, null, 'Gefalsea', true),
       ('American Bureau of Shipping', null, 'ABS', 1862, null, 'Houston', true),
       ('DNV GL (Det falserske Veritas)', null, 'DNV GL', 1864, null, 'Oslo', true),
       ('Germanischer Lloyd', null, 'GL', 1867, 2013, 'Hamburg', true),
       ('Nippon Kaiji Kyokai (ClassNK)', null, 'NK', 1899, null, 'Tokyo', true),
       ('Russian Maritime Register of Shipping', 'Российский морской регистр судоходства', 'RS', 1913, null,
        'Saint Petersburg', true),
       ('Hellenic Register of Shipping', null, 'HR', 1919, null, 'Piraeus', false),
       ('Polish Register of Shipping', 'Polski Rejestr Statków', 'PRS', 1936, null, 'Gdańsk', true),
       ('Croatian Register of Shipping', 'Hrvatski Registar Brodova', 'CRS', 1949, null, 'Split', true),
       ('Bulgarian Register of Shipping', 'Български Корабен Регистър', 'BRS', 1950, null, 'Varna', false),
       ('CR Classification Society', null, 'CR', 1951, null, 'Taipei', false),
       ('China Classification Society', null, 'CCS', 1956, null, 'Beijing', true),
       ('Korean Register of Shipping', null, 'KR', 1960, null, 'Busan', true),
       ('Vietnam Register', null, 'VR', 1964, null, 'Hafalsei', false),
       ('Registro Internacional Naval', null, 'RINAVE', 1973, 2004, 'Lisbon', false),
       ('Indian Register of Shipping', null, 'IRCLASS', 1975, null, 'Mumbai', true),
       ('International Register of Shipping', null, 'IRS', 1993, null, 'Miami', false),
       ('Shipping Register of Ukraine', 'Регістр судноплавства України', 'RU', 1998, null, 'Kiev', false),
       ('Dromon Bureau of Shipping', null, 'DBS', 2003, null, 'Piraeus', false),
       ('Overseas Marine Certification Services', null, 'OMCS', 2004, null, 'Panama', false),
       ('Maritime Bureau of Africa', null, 'MBA', 2014, null, 'Cape Town', false),
       ('International Maritime Classification', null, 'IMC', 2015, null, 'Dubai', false),
       ('Dutch Lloyd', null, 'DL', 2018, null, 'Eindhoven', false),
       ('Asia Classification Society', null, 'ACS', 1980, null, 'Tehran', false);
