INSERT INTO country2 (short_name_nl, short_name_en, alpha2code, alpha3code, numeric_code) VALUES
('Afghanistan', 'Afghanistan', 'AF', 'AFG', 004),
('Albania', 'Albania', 'AL', 'ALB', 008),
('Ãland Islands', 'Aland Islands', 'AX', 'ALA', 248),
('Algerije', 'Algeria', 'DZ', 'DZA', 012),
('Amerikaans-Samoa', 'American Samoa', 'AS', 'ASM', 016),
('Andorra', 'Andorra', 'AD', 'AND', 020),
('Angola', 'Angola', 'AO', 'AGO', 024),
('Anguilla', 'Anguilla', 'AI', 'AIA', 660),
('Antarctica', 'Antarctica', 'AQ', 'ATA', 010),
('Antigua en Barbuda', 'Antigua and Barbuda', 'AG', 'ATG', 028),
('Argentinië', 'Argentina', 'AR', 'ARG', 032),
('Armenië', 'Armenia', 'AM', 'ARM', 051),
('Aruba', 'Aruba', 'AW', 'ABW', 533),
('Australië', 'Australia', 'AU', 'AUS', 036),
('Oostenrijk', 'Austria', 'AT', 'AUT', 040),
('Azerbeidzjan', 'Azerbaijan', 'AZ', 'AZE', 031),
('Bahama''s', 'Bahamas', 'BS', 'BHS', 044),
('Bahrein', 'Bahrain', 'BH', 'BHR', 048),
('Bangladesh', 'Bangladesh', 'BD', 'BGD', 050),
('Barbados', 'Barbados', 'BB', 'BRB', 052),
('Wit-Rusland', 'Belarus', 'BY', 'BLR', 112),
('België', 'Belgium', 'BE', 'BEL', 056),
('Belize', 'Belize', 'BZ', 'BLZ', 084),
('Benin', 'Benin', 'BJ', 'BEN', 204),
('Bermuda', 'Bermuda', 'BM', 'BMU', 060),
('Bhutan', 'Bhutan', 'BT', 'BTN', 064),
('Bolivia', 'Bolivia (Plurinational State of)', 'BO', 'BOL', 068),
('Caribisch Nederland', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', 535),
('Bosnië en Herzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH', 070),
('Botswana', 'Botswana', 'BW', 'BWA', 072),
('Bouveteiland', 'Bouvet Island', 'BV', 'BVT', 074),
('Brazilië', 'Brazil', 'BR', 'BRA', 076),
('Brits Indische Oceaanterritorium', 'British Indian Ocean Territory', 'IO', 'IOT', 086),
('Brunei', 'Brunei Darussalam', 'BN', 'BRN', 096),
('Bulgarije', 'Bulgaria', 'BG', 'BGR', 100),
('Burkina Faso', 'Burkina Faso', 'BF', 'BFA', 854),
('Burundi', 'Burundi', 'BI', 'BDI', 108),
('Kaapverdië', 'Cabo Verde', 'CV', 'CPV', 132),
('Cambodja', 'Cambodia', 'KH', 'KHM', 116),
('Kameroen', 'Cameroon', 'CM', 'CMR', 120),
('Canada', 'Canada', 'CA', 'CAN', 124),
('Kaaimaneilanden', 'Cayman Islands', 'KY', 'CYM', 136),
('Centraal-Afrikaanse Republiek', 'Central African Republic', 'CF', 'CAF', 140),
('Tsjaad', 'Chad', 'TD', 'TCD', 148),
('Chili', 'Chile', 'CL', 'CHL', 152),
('China', 'China', 'CN', 'CHN', 156),
('Christmaseiland', 'Christmas Island', 'CX', 'CXR', 162),
('Cocoseilanden', 'Cocos (Keeling) Islands', 'CC', 'CCK', 166),
('Colombia', 'Colombia', 'CO', 'COL', 170),
('Comoren', 'Comoros', 'KM', 'COM', 174),
('Congo-Brazzaville', 'Congo', 'CG', 'COG', 178),
('Congo-Kinshasa', 'Congo, Democratic Republic of the', 'CD', 'COD', 180),
('Cookeilanden', 'Cook Islands', 'CK', 'COK', 184),
('Costa Rica', 'Costa Rica', 'CR', 'CRI', 188),
('Ivoorkust', 'Cote d''Ivoire', 'CI', 'CIV', 384),
('Kroatië', 'Croatia', 'HR', 'HRV', 191),
('Cuba', 'Cuba', 'CU', 'CUB', 192),
('Curaçao', 'Curacao', 'CW', 'CUW', 531),
('Cyprus', 'Cyprus', 'CY', 'CYP', 196),
('Tsjechië', 'Czechia', 'CZ', 'CZE', 203),
('Denemarken', 'Denmark', 'DK', 'DNK', 208),
('Djibouti', 'Djibouti', 'DJ', 'DJI', 262),
('Dominica', 'Dominica', 'DM', 'DMA', 212),
('Dominicaanse Republiek', 'Dominican Republic', 'DO', 'DOM', 214),
('Ecuador', 'Ecuador', 'EC', 'ECU', 218),
('Egypte', 'Egypt', 'EG', 'EGY', 818),
('El Salvador', 'El Salvador', 'SV', 'SLV', 222),
('Equatoriaal-Guinea', 'Equatorial Guinea', 'GQ', 'GNQ', 226),
('Eritrea', 'Eritrea', 'ER', 'ERI', 232),
('Estland', 'Estonia', 'EE', 'EST', 233),
('Swaziland', 'Eswatini', 'SZ', 'SWZ', 748),
('Ethiopië', 'Ethiopia', 'ET', 'ETH', 231),
('Falklandeilanden', 'Falkland Islands (Malvinas)', 'FK', 'FLK', 238),
('Faeröer', 'Faroe Islands', 'FO', 'FRO', 234),
('Fiji', 'Fiji', 'FJ', 'FJI', 242),
('Finland', 'Finland', 'FI', 'FIN', 246),
('Frankrijk', 'France', 'FR', 'FRA', 250),
('Frans-Guyana', 'French Guiana', 'GF', 'GUF', 254),
('Frans-Polynesië', 'French Polynesia', 'PF', 'PYF', 258),
('Franse Zuidelijke en Antarctische Gebieden', 'French Southern Territories', 'TF', 'ATF', 260),
('Gabon', 'Gabon', 'GA', 'GAB', 266),
('Gambia', 'Gambia', 'GM', 'GMB', 270),
('Georgië', 'Georgia', 'GE', 'GEO', 268),
('Duitsland', 'Germany', 'DE', 'DEU', 276),
('Ghana', 'Ghana', 'GH', 'GHA', 288),
('Gibraltar', 'Gibraltar', 'GI', 'GIB', 292),
('Griekenland', 'Greece', 'GR', 'GRC', 300),
('Groenland', 'Greenland', 'GL', 'GRL', 304),
('Grenada', 'Grenada', 'GD', 'GRD', 308),
('Guadeloupe', 'Guadeloupe', 'GP', 'GLP', 312),
('Guam', 'Guam', 'GU', 'GUM', 316),
('Guatemala', 'Guatemala', 'GT', 'GTM', 320),
('Guernsey', 'Guernsey', 'GG', 'GGY', 831),
('Guinee', 'Guinea', 'GN', 'GIN', 324),
('Guinee-Bissau', 'Guinea-Bissau', 'GW', 'GNB', 624),
('Guyana', 'Guyana', 'GY', 'GUY', 328),
('Haïti', 'Haiti', 'HT', 'HTI', 332),
('Heard en McDonaldeilanden', 'Heard Island and McDonald Islands', 'HM', 'HMD', 334),
('Vaticaanstad', 'Vatican City', 'VA', 'VAT', 336),
('Honduras', 'Honduras', 'HN', 'HND', 340),
('Hongkong', 'Hong Kong', 'HK', 'HKG', 344),
('Hongarije', 'Hungary', 'HU', 'HUN', 348),
('IJsland', 'Iceland', 'IS', 'ISL', 352),
('India', 'India', 'IN', 'IND', 356),
('Indonesië', 'Indonesia', 'ID', 'IDN', 360),
('Iran', 'Iran (Islamic Republic of)', 'IR', 'IRN', 364),
('Irak', 'Iraq', 'IQ', 'IRQ', 368),
('Ierland', 'Ireland', 'IE', 'IRL', 372),
('Man', 'Isle of Man', 'IM', 'IMN', 833),
('Israël', 'Israel', 'IL', 'ISR', 376),
('Italië', 'Italy', 'IT', 'ITA', 380),
('Jamaica', 'Jamaica', 'JM', 'JAM', 388),
('Japan', 'Japan', 'JP', 'JPN', 392),
('Jersey', 'Jersey', 'JE', 'JEY', 832),
('Jordanië', 'Jordan', 'JO', 'JOR', 400),
('Kazachstan', 'Kazakhstan', 'KZ', 'KAZ', 398),
('Kenia', 'Kenya', 'KE', 'KEN', 404),
('Kiribati', 'Kiribati', 'KI', 'KIR', 296),
('Noord-Korea', 'Korea (Democratic People''s Republic of)', 'KP', 'PRK', 408),
('Zuid-Korea', 'Korea, Republic of', 'KR', 'KOR', 410),
('Koeweit', 'Kuwait', 'KW', 'KWT', 414),
('Kirgizië', 'Kyrgyzstan', 'KG', 'KGZ', 417),
('Laos', 'Lao People''s Democratic Republic', 'LA', 'LAO', 418),
('Letland', 'Latvia', 'LV', 'LVA', 428),
('Libanon', 'Lebanon', 'LB', 'LBN', 422),
('Lesotho', 'Lesotho', 'LS', 'LSO', 426),
('Liberia', 'Liberia', 'LR', 'LBR', 430),
('Libië', 'Libya', 'LY', 'LBY', 434),
('Liechtenstein', 'Liechtenstein', 'LI', 'LIE', 438),
('Litouwen', 'Lithuania', 'LT', 'LTU', 440),
('Luxemburg', 'Luxembourg', 'LU', 'LUX', 442),
('Macau', 'Macao', 'MO', 'MAC', 446),
('Madagaskar', 'Madagascar', 'MG', 'MDG', 450),
('Malawi', 'Malawi', 'MW', 'MWI', 454),
('Maleisië', 'Malaysia', 'MY', 'MYS', 458),
('Maldiven', 'Maldives', 'MV', 'MDV', 462),
('Mali', 'Mali', 'ML', 'MLI', 466),
('Malta', 'Malta', 'MT', 'MLT', 470),
('Marshalleilanden', 'Marshall Islands', 'MH', 'MHL', 584),
('Martinique', 'Martinique', 'MQ', 'MTQ', 474),
('Mauritanië', 'Mauritania', 'MR', 'MRT', 478),
('Mauritius', 'Mauritius', 'MU', 'MUS', 480),
('Mayotte', 'Mayotte', 'YT', 'MYT', 175),
('Mexico', 'Mexico', 'MX', 'MEX', 484),
('Micronesia', 'Micronesia (Federated States of)', 'FM', 'FSM', 583),
('Moldavië', 'Moldova, Republic of', 'MD', 'MDA', 498),
('Monaco', 'Monaco', 'MC', 'MCO', 492),
('Mongolië', 'Mongolia', 'MN', 'MNG', 496),
('Montenegro', 'Montenegro', 'ME', 'MNE', 499),
('Montserrat', 'Montserrat', 'MS', 'MSR', 500),
('Marokko', 'Morocco', 'MA', 'MAR', 504),
('Mozambique', 'Mozambique', 'MZ', 'MOZ', 508),
('Myanmar', 'Myanmar', 'MM', 'MMR', 104),
('Namibië', 'Namibia', 'NA', 'NAM', 516),
('Nauru', 'Nauru', 'NR', 'NRU', 520),
('Nepal', 'Nepal', 'NP', 'NPL', 524),
('Nederland', 'Netherlands', 'NL', 'NLD', 528),
('Nieuw-Caledonië', 'New Caledonia', 'NC', 'NCL', 540),
('Nieuw-Zeeland', 'New Zealand', 'NZ', 'NZL', 554),
('Nicaragua', 'Nicaragua', 'NI', 'NIC', 558),
('Niger', 'Niger', 'NE', 'NER', 562),
('Nigeria', 'Nigeria', 'NG', 'NGA', 566),
('Niue', 'Niue', 'NU', 'NIU', 570),
('Norfolk', 'Norfolk Island', 'NF', 'NFK', 574),
('Noord-Macedonië', 'North Macedonia', 'MK', 'MKD', 807),
('Noordelijke Marianen', 'Northern Mariana Islands', 'MP', 'MNP', 580),
('Noorwegen', 'Norway', 'NO', 'NOR', 578),
('Oman', 'Oman', 'OM', 'OMN', 512),
('Pakistan', 'Pakistan', 'PK', 'PAK', 586),
('Palau', 'Palau', 'PW', 'PLW', 585),
('Palestina', 'Palestine, State of', 'PS', 'PSE', 275),
('Panama', 'Panama', 'PA', 'PAN', 591),
('Papoea-Nieuw-Guinea', 'Papua New Guinea', 'PG', 'PNG', 598),
('Paraguay', 'Paraguay', 'PY', 'PRY', 600),
('Peru', 'Peru', 'PE', 'PER', 604),
('Filipijnen', 'Philippines', 'PH', 'PHL', 608),
('Pitcairneilanden', 'Pitcairn', 'PN', 'PCN', 612),
('Polen', 'Poland', 'PL', 'POL', 616),
('Portugal', 'Portugal', 'PT', 'PRT', 620),
('Puerto Rico', 'Puerto Rico', 'PR', 'PRI', 630),
('Qatar', 'Qatar', 'QA', 'QAT', 634),
('Réunion', 'Reunion', 'RE', 'REU', 638),
('Roemenië', 'Romania', 'RO', 'ROU', 642),
('Rusland', 'Russian Federation', 'RU', 'RUS', 643),
('Rwanda', 'Rwanda', 'RW', 'RWA', 646),
('Saint-BarthÃ©lemy', 'Saint Barthélemy', 'BL', 'BLM', 652),
('Sint-Helena, Ascension en Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', 654),
('Saint Kitts en Nevis', 'Saint Kitts and Nevis', 'KN', 'KNA', 659),
('Saint Lucia', 'Saint Lucia', 'LC', 'LCA', 662),
('Sint-Maarten', 'Saint Martin (French part)', 'MF', 'MAF', 663),
('Saint-Pierre en Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM', 666),
('Saint Vincent en de Grenadines', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 670),
('Samoa', 'Samoa', 'WS', 'WSM', 882),
('San Marino', 'San Marino', 'SM', 'SMR', 674),
('Sao Tomé en Principe', 'Sao Tome and Principe', 'ST', 'STP', 678),
('Saoedi-Arabië', 'Saudi Arabia', 'SA', 'SAU', 682),
('Senegal', 'Senegal', 'SN', 'SEN', 686),
('Servië', 'Serbia', 'RS', 'SRB', 688),
('Seychellen', 'Seychelles', 'SC', 'SYC', 690),
('Sierra Leone', 'Sierra Leone', 'SL', 'SLE', 694),
('Singapore', 'Singapore', 'SG', 'SGP', 702),
('Sint Maarten', 'Sint Maarten (Dutch part)', 'SX', 'SXM', 534),
('Slowakije', 'Slovakia', 'SK', 'SVK', 703),
('Slovenië', 'Slovenia', 'SI', 'SVN', 705),
('Salomonseilanden', 'Solomon Islands', 'SB', 'SLB', 090),
('Somalië', 'Somalia', 'SO', 'SOM', 706),
('Zuid-Afrika', 'South Africa', 'ZA', 'ZAF', 710),
('Zuid-Georgia en de Zuidelijke Sandwicheilanden', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239),
('Zuid-Soedan', 'South Sudan', 'SS', 'SSD', 728),
('Spanje', 'Spain', 'ES', 'ESP', 724),
('Sri Lanka', 'Sri Lanka', 'LK', 'LKA', 144),
('Soedan', 'Sudan', 'SD', 'SDN', 729),
('Suriname', 'Suriname', 'SR', 'SUR', 740),
('Spitsbergen en Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM', 744),
('Zweden', 'Sweden', 'SE', 'SWE', 752),
('Zwitserland', 'Switzerland', 'CH', 'CHE', 756),
('Syrië', 'Syrian Arab Republic', 'SY', 'SYR', 760),
('Taiwan', 'Taiwan, Province of China', 'TW', 'TWN', 158),
('Tadzjikistan', 'Tajikistan', 'TJ', 'TJK', 762),
('Tanzania', 'Tanzania, United Republic of', 'TZ', 'TZA', 834),
('Thailand', 'Thailand', 'TH', 'THA', 764),
('Oost-Timor', 'Timor-Leste', 'TL', 'TLS', 626),
('Togo', 'Togo', 'TG', 'TGO', 768),
('Tokelau', 'Tokelau', 'TK', 'TKL', 772),
('Tonga', 'Tonga', 'TO', 'TON', 776),
('Trinidad en Tobago', 'Trinidad and Tobago', 'TT', 'TTO', 780),
('Tunesië', 'Tunisia', 'TN', 'TUN', 788),
('Turkije', 'Turkey', 'TR', 'TUR', 792),
('Turkmenistan', 'Turkmenistan', 'TM', 'TKM', 795),
('Turks- en Caicoseilanden', 'Turks and Caicos Islands', 'TC', 'TCA', 796),
('Tuvalu', 'Tuvalu', 'TV', 'TUV', 798),
('Oeganda', 'Uganda', 'UG', 'UGA', 800),
('Oekraïne', 'Ukraine', 'UA', 'UKR', 804),
('Verenigde Arabische Emiraten', 'United Arab Emirates', 'AE', 'ARE', 784),
('Verenigd Koninkrijk', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 826),
('Verenigde Staten', 'United States of America', 'US', 'USA', 840),
('Kleine afgelegen eilanden van de Verenigde Staten', 'United States Minor Outlying Islands', 'UM', 'UMI', 581),
('Uruguay', 'Uruguay', 'UY', 'URY', 858),
('Oezbekistan', 'Uzbekistan', 'UZ', 'UZB', 860),
('Vanuatu', 'Vanuatu', 'VU', 'VUT', 548),
('Venezuela', 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 862),
('Vietnam', 'Viet Nam', 'VN', 'VNM', 704),
('Britse Maagdeneilanden', 'Virgin Islands (British)', 'VG', 'VGB', 092),
('Amerikaanse Maagdeneilanden', 'Virgin Islands (U.S.)', 'VI', 'VIR', 850),
('Wallis en Futuna', 'Wallis and Futuna', 'WF', 'WLF', 876),
('Westelijke Sahara', 'Western Sahara', 'EH', 'ESH', 732),
('Jemen', 'Yemen', 'YE', 'YEM', 887),
('Zambia', 'Zambia', 'ZM', 'ZMB', 894),
('Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE', 716);
